apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  SECURITY_JWT_SECRET_KEY: {{ .Values.auth.jwtSecret | quote }}
